import Head from "next/head";
import { React } from "react";
import Header from "../components/Header";
import SwiperSliderComponent from "../components/SwiperSliderComponent";
import WhoWeAre from "../components/WhoWeAre";

export default function Home() {
	return (
		<div className="text-[#e7e7e7] uppercase">
			<Head>
				<title>agency music</title>
				<meta name="description" content="Generated by agency music" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<SwiperSliderComponent />
			<WhoWeAre />
		</div>
	);
}
