import Head from "next/head";
import { React, useRef } from "react";
import Awwards from "../components/Awwards";
import Concepts from "../components/Concepts";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Office from "../components/Office";
import Publications from "../components/Publications";
import SwiperSliderComponent from "../components/SwiperSliderComponent";
import WhoWeAre from "../components/WhoWeAre";

export default function Home() {
  // const el = useRef();
  // const q = gsap.utils.selector(el);
  // gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

  // useLayoutEffect(() => {
  //   let smoother = ScrollSmoother.create({
  //     smooth: 1, // how long (in seconds) it takes to "catch up" to the native scroll position
  //     effects: true, // looks for data-speed and data-lag attributes on elements
  //   });
  //   return () => {
  //     smoother.kill();
  //   };
  // }, []);

  return (
    <div className="text-[#e7e7e7] uppercase" ref={el}>
      <Head>
        <title>agency music</title>
        <meta name="description" content="Generated by agency music" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SwiperSliderComponent />
      <WhoWeAre />
      <Concepts />
      <Publications />
      <Awwards />
      <Office />
      <Footer />
    </div>
  );
}
